<a href="https://colab.research.google.com/github/imannfazal/ml-practice/blob/main/pytorch_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas
import numpy
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [3]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
print(scaler.ndim)
print(scaler.shape)

0
torch.Size([])


In [5]:
#vector
vector = torch.tensor([7, 9])
vector
vector.ndim

1

In [6]:
tensor = torch.tensor([[1,-2,-3],[3,4,5],[3,9,7],[0,1,0],[7,8,9]], dtype=torch.float32)
print(tensor)
tensor.ndim

tensor([[ 1., -2., -3.],
        [ 3.,  4.,  5.],
        [ 3.,  9.,  7.],
        [ 0.,  1.,  0.],
        [ 7.,  8.,  9.]])


2

In [7]:
tensor.shape

torch.Size([5, 3])

In [8]:
tensor[1][1] =0
print(tensor)


tensor([[ 1., -2., -3.],
        [ 3.,  0.,  5.],
        [ 3.,  9.,  7.],
        [ 0.,  1.,  0.],
        [ 7.,  8.,  9.]])


In [9]:
scaler.item()

7

In [10]:
torch.FloatTensor.abs_(tensor)

tensor([[1., 2., 3.],
        [3., 0., 5.],
        [3., 9., 7.],
        [0., 1., 0.],
        [7., 8., 9.]])

In [21]:
z = torch.rand(size=(3,5))
z= z+1


In [12]:
z.type(torch.int32)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [18]:
zero = torch.ones(size=(2,3), dtype=torch.int16)
zero

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

**Range of numbers:**

In [14]:
y = torch.arange(0,10)
y

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
z = torch.arange(start=11, end=133, step=11)
z

tensor([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132])

In [16]:
torch.zeros_like(input=z)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Matrix Multiplication:**

In [22]:
c = torch.matmul(z, tensor)
c

tensor([[18.1715, 30.0819, 32.3891],
        [17.6549, 25.0287, 31.1471],
        [21.6682, 30.3059, 34.9535]])

**Transpose:**

In [24]:
c.T

tensor([[18.1715, 17.6549, 21.6682],
        [30.0819, 25.0287, 30.3059],
        [32.3891, 31.1471, 34.9535]])

**Sum, Min, Max, Mean:**
- c.sum()
- c.min()
- c.max()
- c.mean()

In [25]:
c.sum()

tensor(241.4009)

#### **Positional maximum = argmax, Positional minimum = argmin**
Returns index of where the max or min is:

In [26]:
print("Positional minimum: ", c.T.argmin())
print("Positional maximum: ", c.T.argmax())

Positional minimum:  tensor(1)
Positional maximum:  tensor(8)


#### Reshaping, Stacking, Squeezing, Unsqueezing, Permute


In [27]:
x = torch.arange(0,10, dtype=torch.float32)
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
x.reshape(10,1)  #2*5=10

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [29]:
z = x.view(5,2)
z

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]])

In [31]:
#changing z will also change x
z[:,0]=5

In [32]:
z,x

(tensor([[5., 1.],
         [5., 3.],
         [5., 5.],
         [5., 7.],
         [5., 9.]]),
 tensor([5., 1., 5., 3., 5., 5., 5., 7., 5., 9.]))

In [33]:
torch.hstack([x,x,x,x]) #side by side

tensor([5., 1., 5., 3., 5., 5., 5., 7., 5., 9., 5., 1., 5., 3., 5., 5., 5., 7.,
        5., 9., 5., 1., 5., 3., 5., 5., 5., 7., 5., 9., 5., 1., 5., 3., 5., 5.,
        5., 7., 5., 9.])

In [34]:
torch.vstack([x,x,x,x]) #on top of each other

tensor([[5., 1., 5., 3., 5., 5., 5., 7., 5., 9.],
        [5., 1., 5., 3., 5., 5., 5., 7., 5., 9.],
        [5., 1., 5., 3., 5., 5., 5., 7., 5., 9.],
        [5., 1., 5., 3., 5., 5., 5., 7., 5., 9.]])

In [35]:
torch.stack([x,x,x,x], dim=0)

tensor([[5., 1., 5., 3., 5., 5., 5., 7., 5., 9.],
        [5., 1., 5., 3., 5., 5., 5., 7., 5., 9.],
        [5., 1., 5., 3., 5., 5., 5., 7., 5., 9.],
        [5., 1., 5., 3., 5., 5., 5., 7., 5., 9.]])

In [36]:
torch.squeeze(x)

tensor([5., 1., 5., 3., 5., 5., 5., 7., 5., 9.])

In [38]:
f = torch.zeros(2, 1, 2, 1, 2)
f.size(), f

(torch.Size([2, 1, 2, 1, 2]),
 tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]))

In [39]:
v = torch.squeeze(f,1) #only squeezes 1 of 1-D

In [40]:
v.size()

torch.Size([2, 2, 1, 2])

In [41]:
l = v.unsqueeze(dim=2)
l

tensor([[[[[0., 0.]]],


         [[[0., 0.]]]],



        [[[[0., 0.]]],


         [[[0., 0.]]]]])

In [42]:
l.size()

torch.Size([2, 2, 1, 1, 2])

In [43]:
p= l.permute(4,2,1,0,3)
p

tensor([[[[[0.],
           [0.]],

          [[0.],
           [0.]]]],



        [[[[0.],
           [0.]],

          [[0.],
           [0.]]]]])

In [44]:
p.size()

torch.Size([2, 1, 2, 2, 1])

In [45]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [54]:
x[0][2][0]=8

In [55]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [8, 8, 9]]])

In [56]:
x[0][2][2]

tensor(9)

In [62]:
x[0,:,2]

tensor([3, 6, 9])

### **PyTorch & NumPy**
* Data in numPy, want in torch tensor: torch.from_numpy(ndarray)
* torch -> numpy: torch.Tensor.numpy()

In [75]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

In [76]:
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

**Default dtype:**
* numPy: float64
* pyTorch: float32
pytorch reflects numpy dtype when converting from numpy to torch tensor.

In [77]:
tonumpy = tensor.numpy()

In [78]:
tonumpy

array([1., 2., 3., 4., 5., 6., 7.])

In [79]:
tensor = tensor + 1
tonumpy, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

## **Reproducibility** (trying to take random out of random)
* Random seed

In [88]:
import torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
ran1 = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
ran2 = torch.rand(3,4)

ran1==ran2

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Putting tensors on GPU

In [2]:
import torch

tensor = torch.tensor([1,2,3,4,5], device='cuda')


In [8]:
tensor.device

'cpu'

In [7]:
tensor = tensor.cpu().numpy()