<a href="https://colab.research.google.com/github/imannfazal/ml-practice/blob/main/pytorch_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas
import numpy
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [3]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
print(scaler.ndim)
print(scaler.shape)

0
torch.Size([])


In [5]:
#vector
vector = torch.tensor([7, 9])
vector
vector.ndim

1

In [27]:
tensor = torch.tensor([[1,-2,-3],[3,4,5]], dtype=torch.float32)
print(tensor)
tensor.ndim

tensor([[ 1., -2., -3.],
        [ 3.,  4.,  5.]])


2

In [16]:
tensor.shape

torch.Size([2, 3])

In [23]:
tensor[:][1] =0
print(tensor)


tensor([[1., 2., 3.],
        [0., 0., 0.]])


In [25]:
scaler.item()

7

In [28]:
torch.FloatTensor.abs_(tensor)

tensor([[1., 2., 3.],
        [3., 4., 5.]])