<a href="https://colab.research.google.com/github/imannfazal/ml-practice/blob/main/pytorch_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas
import numpy
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [3]:
#scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
print(scaler.ndim)
print(scaler.shape)

0
torch.Size([])


In [5]:
#vector
vector = torch.tensor([7, 9])
vector
vector.ndim

1

In [19]:
tensor = torch.tensor([[1,-2,-3],[3,4,5],[3,9,7],[0,1,0],[7,8,9]], dtype=torch.float32)
print(tensor)
tensor.ndim

tensor([[ 1., -2., -3.],
        [ 3.,  4.,  5.],
        [ 3.,  9.,  7.],
        [ 0.,  1.,  0.],
        [ 7.,  8.,  9.]])


2

In [7]:
tensor.shape

torch.Size([5, 3])

In [8]:
tensor[1][1] =0
print(tensor)


tensor([[ 1., -2., -3.],
        [ 3.,  0.,  5.],
        [ 3.,  9.,  7.],
        [ 0.,  1.,  0.],
        [ 7.,  8.,  9.]])


In [9]:
scaler.item()

7

In [10]:
torch.FloatTensor.abs_(tensor)

tensor([[1., 2., 3.],
        [3., 0., 5.],
        [3., 9., 7.],
        [0., 1., 0.],
        [7., 8., 9.]])

In [20]:
z = torch.rand(size=(3,5))
z= z+1


In [12]:
z.type(torch.int32)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32)

In [13]:
zero = torch.ones(size=(2,3), dtype=torch.int16)
zero

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)

**Range of numbers:**

In [14]:
y = torch.arange(0,10)
y

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
z = torch.arange(start=11, end=133, step=11)
z

tensor([ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132])

In [16]:
torch.zeros_like(input=z)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**Matrix Multiplication:**

In [24]:
c = torch.matmul(z, tensor)
c

tensor([[19.5660, 27.1972, 25.0368],
        [16.2094, 23.6790, 21.4507],
        [17.8525, 26.9270, 21.9145]])

**Transpose:**

In [23]:
c.T

tensor([[19.5660, 16.2094, 17.8525],
        [27.1972, 23.6790, 26.9270],
        [25.0368, 21.4507, 21.9145]])

**Sum, Min, Max, Mean:**
- c.sum()
- c.min()
- c.max()
- c.mean()

In [29]:
c.sum()

tensor(199.8332)

#### **Positional maximum = argmax, Positional minimum = argmin**
Returns index of where the max or min is:

In [41]:
print("Positional minimum: ", c.T.argmin())
print("Positional maximum: ", c.T.argmax())

Positional minimum:  tensor(1)
Positional maximum:  tensor(3)
